spring.application.name=api

# DataSource Settings for PostgreSQL
spring.datasource.url=jdbc:postgresql://172.27.54.110:5432/mydb
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring Security 패키지의 로그 레벨을 DEBUG로 설정
logging.level.org.springframework.security=DEBUG